name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: keys
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Get apikey.properties from secrets
      run: echo "${{secrets.APIKEY_PROPERTIES}}" > $GITHUB_WORKSPACE/apikey.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        SECRET_KEY_FROM_GITHUB: ${{secrets.APIKEY_PROPERTIES}} > $GITHUB_WORKSPACE/apikey.properties
      run: ./gradlew build -PsecretKey="$SECRET_KEY_FROM_GITHUB"
